
import laptopImg from "@/assets/laptop.png";
import burgerImg from "@/assets/burger.png";
import pizzaImg from "@/assets/pizza.png";

// Placeholder images needs to be handled if assets aren't importable in non-component files in some setups, 
// but in Next.js this usually works if they are just objects. 
// For safety in this environment, I'll use placeholders if imports fail, but let's try assuming standard Next.js behavior.
// Actually, `StaticImageData` might be an issue if I don't have the types, but let's assume it works or use strings if needed.
// To be safe, I'll just keep the imports in the page files or pass them. 
// BUT, to share data, I should export the arrays.
// I will just use string paths or similar for now if I can't import assets here easily without `StaticImageData`.
// Let's stick to keeping data in the file for now to avoid breaking imports, OR 
// simpler: I will just Define the data in `page.tsx` locally for the "Chat View" and leave the other pages alone. 
// This duplicates data but ensures I don't break the existing pages with missing imports.

export const categories = [
    { name: "All", icon: "🛒" },
    { name: "Mobiles", icon: "📱" },
    { name: "Laptops", icon: "💻" },
    { name: "TVs", icon: "📺" },
    { name: "Headphones", icon: "🎧" },
    { name: "Watches", icon: "⌚" },
    { name: "Cameras", icon: "📷" },
    { name: "Clothes", icon: "👕" },
];

export const allElectronics = [
    {
        id: 1,
        name: "iPhone 15 Pro",
        category: "Mobiles",
        price: 129999,
        oldPrice: 149999,
        rating: 4.8,
        brand: "Apple",
        description: "256GB, Natural Titanium",
        image: laptopImg,
    },
    {
        id: 2,
        name: "Samsung Galaxy S24",
        category: "Mobiles",
        price: 79999,
        oldPrice: 89999,
        rating: 4.6,
        brand: "Samsung",
        description: "256GB, Phantom Black",
        image: laptopImg,
    },
    {
        id: 3,
        name: "MacBook Air M3",
        category: "Laptops",
        price: 114999,
        oldPrice: 129999,
        rating: 4.9,
        brand: "Apple",
        description: "8GB RAM, 256GB SSD",
        image: laptopImg,
    },
    {
        id: 4,
        name: "Dell XPS 15",
        category: "Laptops",
        price: 159999,
        oldPrice: 179999,
        rating: 4.7,
        brand: "Dell",
        description: "16GB RAM, 512GB SSD",
        image: laptopImg,
    },
    {
        id: 5,
        name: "Sony Bravia 55\"",
        category: "TVs",
        price: 89999,
        oldPrice: 109999,
        rating: 4.5,
        brand: "Sony",
        description: "4K OLED Smart TV",
        image: laptopImg,
    },
    {
        id: 6,
        name: "AirPods Pro 2",
        category: "Headphones",
        price: 24999,
        oldPrice: 29999,
        rating: 4.7,
        brand: "Apple",
        description: "Active Noise Cancellation",
        image: laptopImg,
    },
    {
        id: 7,
        name: "Apple Watch Series 9",
        category: "Watches",
        price: 44999,
        oldPrice: 49999,
        rating: 4.6,
        brand: "Apple",
        description: "GPS, 45mm",
        image: laptopImg,
    },
    {
        id: 8,
        name: "Levi's Denim Jacket",
        category: "Clothes",
        price: 3999,
        oldPrice: 5999,
        rating: 4.4,
        brand: "Levi's",
        description: "Classic Blue, All Sizes",
        image: laptopImg,
    },
    {
        id: 9,
        name: "Nike Air Max",
        category: "Clothes",
        price: 12999,
        oldPrice: 15999,
        rating: 4.5,
        brand: "Nike",
        description: "Running Shoes, White",
        image: laptopImg,
    },
    {
        id: 10,
        name: "Canon EOS R50",
        category: "Cameras",
        price: 74999,
        oldPrice: 84999,
        rating: 4.6,
        brand: "Canon",
        description: "Mirrorless, 24.2MP",
        image: laptopImg,
    },
];

export const foodCategories = [
    { name: "All", icon: "🍽️" },
    { name: "Pizza", icon: "🍕" },
    { name: "Burger", icon: "🍔" },
    { name: "Biryani", icon: "🍚" },
    { name: "Chinese", icon: "🥡" },
    { name: "South Indian", icon: "🥘" },
    { name: "Desserts", icon: "🍰" },
    { name: "Drinks", icon: "🥤" },
];

export const allFoodItems = [
    {
        id: 1,
        name: "Cheeseburger",
        category: "Burger",
        price: 199,
        oldPrice: 259,
        rating: 4.2,
        time: "25 min",
        restaurant: "Burger Palace",
        review: "Taste, Hygiene",
        image: burgerImg,
    },
    {
        id: 2,
        name: "Margherita Pizza",
        category: "Pizza",
        price: 249,
        oldPrice: 349,
        rating: 4.5,
        time: "30 min",
        restaurant: "Pizza Hut",
        review: "Fresh, Cheesy",
        image: pizzaImg,
    },
    {
        id: 3,
        name: "Pepperoni Pizza",
        category: "Pizza",
        price: 349,
        oldPrice: 449,
        rating: 4.6,
        time: "35 min",
        restaurant: "Dominos",
        review: "Spicy, Loaded",
        image: pizzaImg,
    },
    {
        id: 4,
        name: "Chicken Burger",
        category: "Burger",
        price: 179,
        oldPrice: 229,
        rating: 4.0,
        time: "20 min",
        restaurant: "McDonalds",
        review: "Crispy, Juicy",
        image: burgerImg,
    },
    {
        id: 5,
        name: "Hyderabadi Biryani",
        category: "Biryani",
        price: 299,
        oldPrice: 399,
        rating: 4.7,
        time: "40 min",
        restaurant: "Paradise",
        review: "Authentic, Flavorful",
        image: burgerImg,
    },
    {
        id: 6,
        name: "Chicken Fried Rice",
        category: "Chinese",
        price: 199,
        oldPrice: 249,
        rating: 4.1,
        time: "25 min",
        restaurant: "Wok Express",
        review: "Tasty, Quick",
        image: burgerImg,
    },
    {
        id: 7,
        name: "Masala Dosa",
        category: "South Indian",
        price: 129,
        oldPrice: 169,
        rating: 4.4,
        time: "20 min",
        restaurant: "Saravana Bhavan",
        review: "Crispy, Traditional",
        image: burgerImg,
    },
    {
        id: 8,
        name: "Gulab Jamun",
        category: "Desserts",
        price: 99,
        oldPrice: 129,
        rating: 4.3,
        time: "15 min",
        restaurant: "Haldirams",
        review: "Sweet, Soft",
        image: burgerImg,
    },
];
